INSERT INTO route_prices
VALUES (1, 70);
INSERT INTO route_prices
VALUES (2, 70);
INSERT INTO route_prices
VALUES (3, 38);
INSERT INTO route_prices
VALUES (4, 38);
INSERT INTO route_prices
VALUES (5, 30);
INSERT INTO route_prices
VALUES (6, 30);
INSERT INTO route_prices
VALUES (7, 25);
INSERT INTO route_prices
VALUES (8, 25);
INSERT INTO route_prices
VALUES (9, 40);
INSERT INTO route_prices
VALUES (10, 40);
INSERT INTO route_prices
VALUES (11, 55);
INSERT INTO route_prices
VALUES (12, 55);
INSERT INTO route_prices
VALUES (13, 28);
INSERT INTO route_prices
VALUES (14, 28);
INSERT INTO route_prices
VALUES (15, 20);
INSERT INTO route_prices
VALUES (16, 20);
INSERT INTO route_prices
VALUES (17, 15);
INSERT INTO route_prices
VALUES (18, 15);